### ISSUE TITLE
Why did this repository got excluded from hacktoberfest 2022?

### ISSUE THREAD

**Issue by Baba-Yaga-1** [adielliot37/dsa#38]
After my PR got merged, I got an update in hacktoberfest profile that this repository has been excluded from the event .
Even though hacktoberfest-accepted label was added.

![Screenshot 2022-10-03 at 16-06-45 Profile Hacktoberfest 2022](https://user-images.githubusercontent.com/56999749/193557749-ec1ac152-b98d-464d-9d85-ca28f05d3177.png)

**Comment by priyanshd** [comment]
The whole idea of Open Source and Hacktoberfest is to encourage people to work on real problems, not submitting DSA solutions. Repositories that are creating spammy issues with DSA problems are being archived, since that's against the code of conduct of Hacktoberfest.
Find a real problem to contribute to. Cheers!

**Comment by Baba-Yaga-1** [comment]
> The whole idea of Open Source and Hacktoberfest is to encourage people to work on real problems, not submitting DSA solutions. Repositories that are creating spammy issues with DSA problems are being archived, since that's against the code of conduct of Hacktoberfest. Find a real problem to contribute to. Cheers!

Okay, got it.
Thanks.
